# Generated by Django 4.1.13 on 2024-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("CourseId", models.AutoField(primary_key=True, serialize=False)),
                ("University", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=50)),
                ("Country", models.CharField(max_length=50)),
                ("CourseName", models.CharField(max_length=50)),
                ("CourseDescription", models.CharField(max_length=500)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Currency", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "coursesapp_courses",
            },
        ),
    ]
