# Generated by Django 4.1.13 on 2024-07-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='coursesapp_courses',
        ),
    ]
