# Generated by Django 4.1.13 on 2024-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0002_alter_courses_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table=None,
        ),
    ]
