# Generated by Django 4.1.13 on 2024-07-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0003_alter_courses_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='normalized_data',
        ),
    ]
